### ISSUE TITLE
Request for Evaluation Code Release

### ISSUE THREAD

**Issue by hq-fang** [pipixiaqishi1/SAM-E#3]
Hi!

First of all, thank you for sharing your impressive work on SAM-E. We are currently working on replicating the results based on this repository. However, we noticed that the evaluation code has not been released, despite several months having passed since the initial release.

Could you please share an update on when the evaluation code might be available? Any estimated timeline or guidance would be greatly appreciated.

Thank you in advance!

**Comment by hengyuan-zhang-0** [comment]
Thank you for your excellent work! I’m especially interested in the evaluation part of your code, but as a beginner, I find it challenging to fully understand without access to the evalution code. If possible, could you consider open-sourcing the evalution  code for this project?

Best regards,

**Comment by pipixiaqishi1** [comment]
Thanks for all your interest in our work. The evaluation is updated; feel free to contact us if you have any problems.
