### ISSUE TITLE
Request for Model Weight Release

### ISSUE THREAD

**Issue by hq-fang** [pipixiaqishi1/SAM-E#4]
Hello,

First of all, thank you for open-sourcing the training and evaluation scripts!

I’m still attempting to replicate the results of the experiments mentioned in the paper. On top of this, I would also like to kindly request access to the SAM-E model weight used in the general multi-task RLBench experiments, which achieves SOTA performances.

Having access to the weight would significantly aid in benchmarking and comparing your results and my replication. Could you please share the model weights or provide any guidance on how I can obtain them?

Thank you in advance for your assistance. Looking forward to your response!

**Comment by pipixiaqishi1** [comment]
Thanks for your valuable advice. We are considering sharing a newly trained checkpoint and the training process will take us several days.

**Comment by pipixiaqishi1** [comment]
Hi, the checkpoint of the multi-task training has been uploaded. Please kindly check them from the readme.
