### ISSUE TITLE
task number

### ISSUE THREAD

**Issue by MingC715** [pipixiaqishi1/SAM-E#5]
Hello author, great work. I have a question, I want to try different number of tasks to train, so I changed the task parameter in the same.yaml file, why does it take me the same amount of time and memory to train 18 tasks as it does to train only a single task?

**Comment by pipixiaqishi1** [comment]
Yes, I think you correctly changed the tasks parameter to the specific name of the tasks for which you want to train the model. However, the memory is determined by bs and model parameters and the training time mainly depends on these two parameters:
https://github.com/pipixiaqishi1/SAM-E/blob/3200fd9f19520ec4f1d6ac4c6036be619abb163d/samE/train.py#L191-L192

The tasks only determine where you sample the data. Hope this can help.

**Comment by MingC715** [comment]
Thank you very much for your reply. I understand what you mean. I will adjust the number of iterations or the number of epochs trained according to the task requirements.

**Comment by pipixiaqishi1** [comment]
Feel free to reopen this issue if you have any questions.
