### ISSUE TITLE
Can this code be implemented on the UR5e robotic arm?

### ISSUE THREAD

**Issue by ZJU-PLP** [pipixiaqishi1/SAM-E#6]
@pipixiaqishi1 
Hi, Junjie:

Thanks for sharing so nice work. Can this code be implemented on the UR5e robotic arm?

**Comment by pipixiaqishi1** [comment]
Hi, we didn't try to deploy SAM-E on the UR5e robotic arm, so I'm afraid I cannot advise on this issue. Theoretically, SAM-E doesn't control the robotic arm directly; in contrast, it does so by providing a target position. It is possible to achieve this by the planner within the specific robotic arm.

**Comment by ZJU-PLP** [comment]
> Hi, we didn't try to deploy SAM-E on the UR5e robotic arm, so I'm afraid I cannot advise on this issue. Theoretically, SAM-E doesn't control the robotic arm directly; in contrast, it does so by providing a target position. It is possible to achieve this by the planner within the specific robotic arm.

Ok, got it. Thanks for your reply.
